const pdfService = require('../src/services/pdfService');
const fs = require('fs');
const path = require('path');

const runTest = async () => {
    try {
        console.log('Testing PDF Generation...');
        const htmlContent = `
            <html>
                <head>
                    <style>body { font-family: sans-serif; padding: 20px; }</style>
                </head>
                <body>
                    <h1>Test Invoice</h1>
                    <p>This is a test PDF generated by Puppeteer.</p>
                    <table border="1" cellpadding="10">
                        <tr><th>Item</th><th>Cost</th></tr>
                        <tr><td>Service A</td><td>$100</td></tr>
                    </table>
                </body>
            </html>
        `;
        const invoiceId = 'test-123';
        
        const { filePath } = await pdfService.generateInvoicePdf(htmlContent, invoiceId);
        
        console.log('PDF Generated at:', filePath);
        
        if (fs.existsSync(filePath)) {
            const stats = fs.statSync(filePath);
            console.log(`PDF Size: ${stats.size} bytes`);
            if (stats.size > 1000) { // Should be at least a few KB
                console.log('✅ PDF generation successful (file size reasonable).');
            } else {
                console.error('⚠️ PDF generation warning (file size very small).');
            }
            
            // Cleanup
            pdfService.deleteFile(filePath);
            console.log('Test file cleaned up.');
        } else {
            console.error('❌ PDF file not found.');
        }
    } catch (error) {
        console.error('❌ Test failed with error:', error);
    }
};

runTest();
